analyzer:
  errors:
    public_member_api_docs: ignore
    inference_failure_on_collection_literal: ignore
    omit_local_variable_types: ignore
    inference_failure_on_function_invocation: ignore
    must_be_immutable: ignore
    depend_on_referenced_packages: ignore
    avoid_dynamic_calls: ignore
    file_names: ignore
include: package:very_good_analysis/analysis_options.6.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
